AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AWS

  Sample SAM Template for AWS

  '
Globals:
  Function:
    Runtime: python3.7
    Timeout: 10
    Environment:
      Variables:
        AIRTABLE_KEY: key3tgXMZ5FNkZZ98
Resources:
  submitNewRetoolProblem:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.submit_problem_handler
      Events:
        CuratedProblem:
          Type: Api
          Properties:
            Path: /submitRetoolProblem
            Method: POST
      CodeUri: s3://bmnt-retool-code-bucket/1b74d660a88dad83613ec3ea204a81c2
  submitUpdatedRetoolProblem:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.updated_problem_handler
      Events:
        UpdatedProblem:
          Type: Api
          Properties:
            Path: /updateRetoolProblem
            Method: POST
      CodeUri: s3://bmnt-retool-code-bucket/1b74d660a88dad83613ec3ea204a81c2
Outputs:
  BMNTRetoolAPI:
    Description: Endpoints for BMNT form logic
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  submitNewRetoolProblem:
    Description: Submit New Problem ARN
    Value:
      Fn::GetAtt:
      - submitNewRetoolProblem
      - Arn
  submitUpdatedRetoolProblem:
    Description: Update Existing Problem ARN
    Value:
      Fn::GetAtt:
      - submitUpdatedRetoolProblem
      - Arn
