AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

Globals:
  Function:
    Runtime: python3.7
    Timeout: 10
    CodeUri: retool_form_code/
    Environment:
      Variables:
        AIRTABLE_KEY: key3tgXMZ5FNkZZ98

Resources:
  submitNewRetoolProblem:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.submit_problem_handler
      Events:
        CuratedProblem:
          Type: Api
          Properties:
            Path: /submitRetoolProblem
            Method: POST
  submitUpdatedRetoolProblem:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.updated_problem_handler
      Events:
        UpdatedProblem:
          Type: Api
          Properties:
            Path: /updateRetoolProblem
            Method: POST

